#
# Module manifest for module 'PSGet_network'
#
# Generated by: tux
#
# Generated on: 10/5/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Network.psm1'

# Version number of this module.
ModuleVersion = '0.9.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '6b5513e0-3efd-4ab7-a717-fd5793f6619b'

# Author of this module
Author = 'Chris Masters'

# Company or vendor of this module
CompanyName = 'Chris Masters'

# Copyright statement for this module
Copyright = '(c) 2017 Chris Masters. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module with various network functions'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ModuleName='core';Guid='7ffd438f-134c-49be-8000-9a9f3af1cbe3';ModuleVersion='1.4'}
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @('ADNetwork.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('Network.psm1','Network.psd1','ADNetwork.ps1')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Network','DNS','web','IP','Address','ifconfig','netstat','cert','certificate','DHCP')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/masters274/Posh_Repo/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/masters274/Posh_Repo'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
Version 0.1
- Day one

Version 0.2
- Function (WEB) Added : Get-WebCertificate
- Function (DNS) Changed : Added progress to the Get-DnsDebugLog 

Version 0.3
- Function (WEB) added : Get-WebSecurityProtocol
- Function (WEB) added : Set-WebSecurityProtocol 
- Function (WEB) added : Import-509Certificate

Version 0.4
- Function (DNS) added : Get-HostsFile : Pretty self explainatory
- Function (DNS) added : Add-HostsFileEntry : Offers elevation if not running as admin
- Function (DNS) added : Remove-HostsFileEntry : Elevation offered. Only IP arg for now. 

Version 0.5
- Function (WEB) added : Expand-Uri : for seeing the destination of a shortened URL w/o going there...
- Function (WEB) changed : Set-WebSecurityProtocol had a problem with looking up current protocols. 
- Function (NET) added : Get-Netstat returns an object with established and listening port info
- Module : changed : Removed the prerequisite installer of the core module. 
- Module : changed : Module now requires PowerShell version 5.0

Version 0.6
- Function (NET) added : Send-WakeOnLan added

Version 0.7
- Function (WEB) added : Disable-Proxy added. Disables IE proxy settings via registry keys. 
- Function (WEB) added : Enable-Proxy added. Enables IE proxy settings via registry keys. 
- Module : changed : now requires core version to be 1.4 or higher

Version 0.7.1
- Function (WEB) updated : Enable-Proxy now tries to figure out if you had proxy or auto URL configured

Version 0.7.2
- Function (WEB) added : Get-Proxy. Returns True or False based on the proxy status

Version 0.8
- Module updated : Changed the requires statement to not include NetAdapter or NetTCPIP. This way it will work with
older operating systems. This will only exclude one function (ifconfig). 

Version 0.9
- Module updated : Cheanged the RequiredVersion, to ModuleVersion
- Function (DNS) : added : Get-DNSScavengeRecord returns records to be scavenged on DNS servers, if you enable it.

Version 0.9.1
- Function (DNS) : added : Invoke-DNSManualCleanUp. Just could not wait to add this one in, thus ver 0.9.!

Version 0.9.2
- Function (DNS) : updated : Invoke-DNSManualCleanUp. Added parameter RRType, just in case you wanna clean PTRs
'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

