#
# Module manifest for module 'PSGet_core'
#
# Generated by: Chris Masters
#
# Generated on: 9/8/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'core.psm1'

# Version number of this module.
ModuleVersion = '1.6'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7ffd438f-134c-49be-8000-9a9f3af1cbe3'

# Author of this module
Author = 'Chris Masters'

# Company or vendor of this module
CompanyName = 'Chris Masters'

# Copyright statement for this module
Copyright = '(c) 2017 Chris Masters. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Module with various generic functions that could be used in any script'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Invoke-DebugIt', 'ConvertTo-Base36', 'Get-LoggedOnUser', 
               'Invoke-EnvironmentalVariable', 'Remove-SymLink', 
               'Get-WindowsLicenseInfo', 'Invoke-Elevate', 'New-HardLink', 
               'ConvertFrom-Base64', 'ConvertFrom-Hexadecimal', 'ConvertTo-Base64', 
               'ConvertFrom-HexToFile', 'Clear-IECachedData', 
               'Invoke-VariableBaseLine', 'Get-ComObject', 'Get-HardLink', 
               'Invoke-Alert', 'ConvertFrom-Base36', 'Invoke-Touch', 
               'Get-IpRemotingTrustedHost', 'Start-ImpersonateUser', 'Add-Signature', 
               'Add-IPRemotingTrustedHost', 'Test-ModuleLoaded', 
               'Open-NotepadPlusPlus', 'New-SymLink', 'ConvertTo-Hexadecimal', 
               'Get-USB', 'Convert-ByteArrayToHex', 'Get-InstalledSoftware', 
               'Invoke-Snitch', 'Invoke-CredentialManager', 'ConvertFrom-DosToUnix', 
               'Test-AdminRights')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
#CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @('Add-Sig', 'Alert', 'Create-SymbolicLink', 'dos2unix', 'elevate', 'Get-EnvironmentalVariable',
 'Get-EnvVar', 'Get-Password', 'Invoke-Logger', 'ln', 'logger', 'New-EnvVar', 'npp', 
 'Remove-EnvironmentalVariable', 'Remove-EnvVar', 'Set-EnvironmentalVariable', 'Set-EnvVar', 'sign', 
 'Store-Credentials', 'sudo', 'touch')


# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('system')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/masters274/Posh_Repo/blob/master/LICENSE'

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
Version 0.3
- Code folding regions added for better navigation and visibility
- Function (SECURITY) added : Test-AdminRights
- Function (SECURITY) added : Start-ImpersonateUser
- Function (SECURITY) added : Get-LoggedOnUser
- Function (SECURITY) added : Invoke-Elevate
- Function (FILESYSTEM) added : Open-Notepad++
- Multiple aliases added for functions
- EventLogging added to Invoke-DebugIt function

Version 0.4
- Function (SECURITY) updated : Invoke-Elevate, "sudo $$" or "sudo $^" now works, similar to "sudo !!"
- Function (DEVELOPMENT) updated : Fixed scope issues with Invoke-VariableBaseLine
- Function (DEVELOPMENT) updated : $boolDebug must be set for -Debug to be recognized in other functions.

Version 0.5
- Function (FILESYSTEM) updated : As cool as it was, renamed Open-Notepad++ to Open-NotepadPlusPlus :(
- Function (FILESYSTEM) added : New alias created for Invoke-Touch = touch
- Function (SECURITY) added : Invoke-CredentailManager, with aliases
- Function (LOG/ALERT) updated : Removed the $boolDebug declaration from this function. This will be
set by the calling function, when -Debug is used. 
- Function (DEVELOPMENT) updated : Now allows you to add the file path to a module not in the default path.
        
Version 0.6
- Function (DEVELOPMENT) added : Invoke-EnvrionmentalVariable
- Function (DEVELOPMENT) added : Invoke-Alert with alias (alert). Audible tone for when you want to
monitor the availability of something while doing some other work. 
- Function (SECURITY) updated : Parameter alias on Invoke-CredentialManager for backward compatibility
- Function (DEVELOPMENT) added : ConvertTo-Hexadecimal
- Function (DEVELOPMENT) added : ConvertFrom-HexToFile. Great way for working with binary files.
- Function (DEVELOPMENT) added : ConvertTo-Base36
- Function (DEVELOPMENT) added : ConvertFrom-Base36
- Function (DEVELOPMENT) added : ConvertTo-Base64
- Function (DEVELOPMENT) added : ConvertFrom-Base64

Version 0.7
- Function (FILESYSTEM) added : New-SymLink
- Function (FILESYSTEM) added : Remove-SymLink
- Function (DEVELOPMENT) updated : Add-Signature. Removed aliases used inside the function.
- Module header information added. 
- Function (LOG/ALERT) moved : Moved Invoke-Alert to Log/Alert region.
- Custom Type : added : MkLink type added. This is needed by several functions.
- Function (SECURITY) : updated : Invoke-Elevate : Removed variable baseline function call. This function 
is typically used in conjunction with other functions, which may be using the baseline functionality. 

Version 0.8
- Function (FILESYSTEM) added : New-HardLink : 
- Alias (FILESYSTEM) : added : Create-SymbolicLink : Easier to remember when trying to thinka about what 
the function actually does. 
- Alias (DEVELOPMENT) : added : New-InvironmentalVarVariable, New-EnvVar, Remove-EnvVar, and 
Remove-EnvironmentalVariable
- Function (SECURITY) : changed : Invoke-Elevate : added an argument for "no profile", instead of this
being the default. Sometimes we need the profile to load custom modules. 
- Function (SECURITY) : changed : Invoke-CredentialManager modified to store user name too.
- Function (DEVELOPMENT) : changed : ConvertFrom-HexToFile updated. Failed on empty directories

Version 0.9
- Functions (ALL) : changed : Removed baselines for functions. This isn''t really needed on these functions.
- Function (SECURITY) : changed : updated Invoke-CredentialManager. Now can return an object from XML

Version 1.0
- Module (core) : updated : moved change log information to module manifest
- Function (FILESYSTEM) : added : Get-HardLink, for finding links to a file. Author: Greg Shields

Version 1.1
- Function (SECURITY) : changed : Invoke-CredentialManager removed ConvertTo-SecureString -AsPlainText command

Version 1.2
- Function (DEVELOPMENT) : added : ConvertFrom-Hexadecimal. Converts hex input to ASCII string
- Function (FILESYSTEM) : added : ConvertFrom-DosToUnix. Replaces CLRF with newline within a file. 

Version 1.3
- Region (SYSTEM) : added : additional functions that fit well into the core module
- Function (SYSTEM) : added : Get-InstalledSoftware, Get-USB, Add-IPRemotingTrustedHost, Get-IpRemotingTrustedHost,
    Clear-IECachedData, Get-ComObject

Version 1.4
- Function (FILESYSTEM) : changed : Invoke-Touch updated to accept value from pipeline. 
- Function (DEVELOPMENT) : added : Convert-ByteArrayToHex. Needed when working with some registry values

Version 1.5
- Function (SYSTEM) : added : Get-WindowsLicenseInfo. Gets a summary of the slmgr output from local or remote.
- Function (SYSTEM) : changed : Get-InstalledSoftware. Now accepts and array of computer names.
- Function (FILESYSTEM) : changed : Invoke-Touch. Ability to force directory type. 

Version 1.6
- Function (SECURITY) : changed : Start-ImpersonateUser. Put password in quotes to escape most characters.
- Function (SYSTEM) : added : Connect-Workstation. Enters a PSSession on a remote computer
- Function (SECURITY) : added : Get-FirewallStatus. Shows if the local firewall is enabled
- Function (SYSTEM) : added : Get-UninstallString. Pulls the uninstall string from the registry for matching pattern
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update
        RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

